### ISSUE TITLE
sequence produces duplicate at the end

### ISSUE THREAD

**Issue by kenn** [zverok/time_math2#8] opened 2017-07-10 01:59 UTC
```ruby
TimeMath.day.sequence((2.days.ago)..Time.current).to_a

=> [Sat, 08 Jul 2017 01:52:04 UTC +00:00,
 Sun, 09 Jul 2017 01:52:04 UTC +00:00,
 Mon, 10 Jul 2017 01:52:04 UTC +00:00,
 Mon, 10 Jul 2017 01:52:04 UTC +00:00]
```

Notice we have a duplicate time object at the end. And then I went to the documentation and found that using `...` instead of `..` solved the problem.

But I wonder if it's a bug, or is there any particular use case that you want to have a duplicate?

Otherwise I think it should be the other way around, making `..` just work and use `...` to produce the excluding behavior, in above case, exclude 10 Jul from result. I can see this can be useful, and that'd be the expected behavior.

What do you think?

**Comment by zverok** [comment] 2017-07-11 14:05
It is not a bug, in fact. Here is explanation:

Inclusive/exclusive end in range means "include / do not include `to` into sequence".
```ruby
t = Time.current
TimeMath.day.sequence(2.days.before(t)..t).to_a
# => [2017-07-09 16:59:09 +0300, 2017-07-10 16:59:09 +0300, 2017-07-11 16:59:09 +0300] 
TimeMath.day.sequence(2.days.before(t)...t).to_a
# => [2017-07-09 16:59:09 +0300, 2017-07-10 16:59:09 +0300]
```
That's how it is designed and documented.

What is the difference with your example? Look:
```ruby
array = TimeMath.day.sequence((2.days.ago)..Time.current).to_a
# => [2017-07-09 17:00:43 +0300, 2017-07-10 17:00:43 +0300, 2017-07-11 17:00:43 +0300, 2017-07-11 17:00:43 +0300] 
#                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#                                                                             duplicates?..
array[-2] == array[-1]
# => false
# NOPE.
array[-1] - array[-2]
# => 0.00014256
# microseconds!
```
E.g. `2.days.ago` and `Time.current` are NOT exactly 2 days different, but 2 days and some microseconds that passed between calculation of those two vars.

So, TimeMath calculated from start, to end, advancing day-by-day... Until final element was last lower than `to`. And if it is not EXACTLY equal to `to` (which it is not), adds `to` to close the sequence.

Time is hard :(

**Comment by kenn** [comment] 2017-07-12 01:26
OMG 😂 Thanks for pointing that out, now I understand the issue.

But that's an internal implementation detail, not an interface's concern, which should be encapsulated nicely by the library. Users shouldn't care about the nuances unless they are dealing with `TimeMath.second.sequence` (in this case it's reasonable to assume they will be aware of the potential timing issue).

From an interface standpoint,

* When we specify "day" for a sequence, our concern is "day".
* Therefore, two time objects are the same at the "day" level and should never be duplicated.
* And if we exclude by `...`, our expectation is to remove "today".
* Apply the same rule to all granularities, treating as if all smaller units are truncated and zero'd out.
  * `Time.new(2017,7,11,0,0,0)` for days, `Time.new(2017,7,11,17,0,0)` for hours, `Date.new(2017,7,11).cweek` for weeks, etc.

So the expected behavior would be:

```ruby
TimeMath.day.sequence((2.days.ago)..Time.current).to_a
=> [Sat, 08 Jul 2017 01:52:04 UTC +00:00,
 Sun, 09 Jul 2017 01:52:04 UTC +00:00,
 Mon, 10 Jul 2017 01:52:04 UTC +00:00]

TimeMath.day.sequence((2.days.ago)...Time.current).to_a
=> [Sat, 08 Jul 2017 01:52:04 UTC +00:00,
 Sun, 09 Jul 2017 01:52:04 UTC +00:00]
```

That way, there will be a lot less (practically none) negative surprises except the absolute edge cases like when you run it at 23:59:59. :)

What do you think?

**Comment by zverok** [comment] 2017-07-13 15:26
TBH, there is not enough cases for me to decide clearly. 
What are you saying is, in fact, making sense. But my orginal idea of this implementation _seem_ to make sense still, too. How it was designed? Consider we have a chart from beginning of month to current moment. 

**NB** While trying to explaining this concept, I believe I've found a bug. So, I'll explain how it SHOULD work, in my head :) Not how it works now.

```ruby
from = Time.new(2017,7,1)
to = Time.now
# 1.
periods = TimeMath.day.sequence(from...to).ranges
#  => ...., 2017-07-12 00:00:00 +0300...2017-07-13 00:00:00 +0300]
# ^ e.g. last range is last FULL day

# 2.
periods = TimeMath.day.sequence(from..to).to_a
# => ...., 2017-07-13 00:00:00 +0300...2017-07-13 18:17:50 +0300] 
# ^ e.g. the same as above + current day
```

There is also `expand: true` option for sequences, which rounds to the nearest full day (for day sequence) both beginning and end... And probably should also consider `..` vs `...` (e.g. round up or down). It probably addresses your "if I get normalized, zero'd out time object" in clean way.

So, I am really indecisive currently. But yes, this part of functionality seems underdesigned definitely. I am open for proposals, just consider my "initial" design ideas discussed above.

**Comment by kenn** [comment] 2017-07-14 11:59
Yeah, I see what you mean.

I think that's the root cause of complexity, by mixing two different classes of objects (seconds and days) in the result of your second `..` example. We probably don't need `expand` option either, which also sounds unclear what it does (sounds like alias to `ceil`?).

To me, it's intuitive to apply `TimeMath.day.floor()` to both `from` and `to` arguments, because that's what happens if you do `Time.current.to_date.to_time`. Normalizing by flooring is the only reliable way to enable round-trip conversion between time and other time scales, so it's the most powerful and versatile proxy representation of coarse-than-second objects, I believe.

**Comment by zverok** [comment] 2017-07-14 14:16
Thanks for your thoughts. I need to consider it for a few moments. BTW, what `expand: true` does is _flooring the begin_ and _ceiling the end:
```ruby
TimeMath.day.sequence(2.days.before(t)..t)
# => #<TimeMath::Sequence(:day, 2017-07-12 17:16:15 +0300..2017-07-14 17:16:15 +0300)> 
TimeMath.day.sequence(2.days.before(t)..t, expand: true)
# => #<TimeMath::Sequence(:day, 2017-07-12 00:00:00 +0300..2017-07-15 00:00:00 +0300)>
```
Maybe instead of the option, we should always round them: always floor the beginning, and floor/ceil end, depending on range's exclusive end?.. :philosoraptor:

**Comment by zverok** [comment] 2017-07-14 14:20
TBH, I still believe the case could exist when you want sequence of hour (minute/day/week) intervals _before the current moment_, not the floored/ceiled moment. But I am not sure I can prove it with real data :) I left the production project on which I've invented the library ~1.5 year ago, and on my current gems requirements are much simpler. But I believe current state of things was deduced from real world cases.

**Comment by kenn** [comment] 2017-07-15 23:40
> Maybe instead of the option, we should always round them: always floor the beginning, and floor/ceil end, depending on range's exclusive end?

My suggestion is always `floor` on both ends. `floor` is the only way to ensure round-trip conversion. You can always do `.advance(day: 1)` if you need the result of `ceil`, however I can't come up with any use case with it, except like `created_at < midnight_tomorrow`. If you need this feature, I would make `ceil: true` as an option, for clarity and consistency with other methods with `TimeMath`.

**Comment by kenn** [comment] 2017-07-17 02:13
I now have another issue.

I have a charting feature that automatically scales back depending on the history length, if less than 30 days `TimeMath.day`, less than 4 months `TimeMath.week`, longer than 4 months `TimeMath.month` using dynamic method call like `TimeMath.send(scale)` internally.

And as I reported here, I'm using `...` to work around the duplicate at the end of the range. But this time, with `TimeMath.month`, the current month (July) is excluded from the result. 

```ruby
> c.range
=> #<TimeMath::Sequence(:month, 2017-02-24 08:25:05 UTC...2017-07-17 01:52:03 UTC)>
> c.range.to_a
=> [Fri, 24 Feb 2017 08:25:05 UTC +00:00,
 2017-03-24 08:25:05 +0000,
 2017-04-24 08:25:05 +0000,
 2017-05-24 08:25:05 +0000,
 2017-06-24 08:25:05 +0000]
```

I thought there would always be a duplicate at the end, and `...` would remove that, but in this case it actually drops the current month. What should I do to work around this?

**Comment by zverok** [comment] 2017-07-17 13:01
But that's exactly what `..` for:
```ruby
TimeMath.month.sequence(Time.parse('2017-02-24 08:25:05 UTC')..Time.parse('2017-07-17 01:52:03 UTC')).to_a
#  => [2017-02-24 08:25:05 UTC, 2017-03-24 08:25:05 +0000, 2017-04-24 08:25:05 +0000, 2017-05-24 08:25:05 +0000, 2017-06-24 08:25:05 +0000, 2017-07-17 01:52:03 UTC]
```
E.g. for `...` sequence consists only of _full monthes_ before `to`, but for `..` -- for _all full monthes and_ `to`. 

What you probably call "duplicates" (two dates in a same month) will emerge if `to`'s day is after `from`'s:
```ruby
TimeMath.month.sequence(Time.parse('2017-02-24 08:25:05 UTC')..Time.parse('2017-07-27 01:52:03 UTC')).to_a
# => [2017-02-24 08:25:05 UTC, 2017-03-24 08:25:05 +0000, 2017-04-24 08:25:05 +0000, 2017-05-24 08:25:05 +0000, 2017-06-24 08:25:05 +0000, 2017-07-24 08:25:05 +0000, 2017-07-27 01:52:03 UTC]
```

For `from` and `to` granulated equaly (exactly same day/time), there would be no "duplicates":
```ruby
TimeMath.month.sequence(Time.parse('2017-02-24 08:25:05 UTC')..Time.parse('2017-07-24 08:25:05 UTC')).to_a
# => [2017-02-24 08:25:05 UTC, 2017-03-24 08:25:05 +0000, 2017-04-24 08:25:05 +0000, 2017-05-24 08:25:05 +0000, 2017-06-24 08:25:05 +0000, 2017-07-24 08:25:05 UTC]
```

Don't you think this behavior IS, in fact, reasonable?..

**Comment by kenn** [comment] 2017-07-17 13:41
> Don't you think this behavior IS, in fact, reasonable?

No, it's just broken to me. Even a few days after we had this conversation, I still can't wrap my head around how it works.

You say:

> What you probably call "duplicates" (two dates in a same month) will emerge if to's day is after from's:

It's easier said than done.

Here's the code example, can you update the code to reliably remove the duplicate (and only duplicate) at the end?

```ruby
def range(since)
  case
  when since < 6.months.ago
    TimeMath.month.sequence(since...Time.current).to_a
  when since < 30.days.ago
    TimeMath.week.sequence(since...Time.current).to_a
  else
    TimeMath.day.sequence(since...Time.current).to_a
  end
end
```

You'll see what I mean.

**Comment by zverok** [comment] 2017-07-19 08:16
```ruby
range(Time.parse('2017-01-01'))
# => [2017-01-01 00:00:00 +0200, 2017-02-01 00:00:00 +0200, 2017-03-01 00:00:00 +0200, 2017-04-01 00:00:00 +0200, 2017-05-01 00:00:00 +0200, 2017-06-01 00:00:00 +0200, 2017-07-01 00:00:00 +0200]
range(Time.parse('2017-03-01'))
# => [2017-03-01 00:00:00 +0200, 2017-03-08 00:00:00 +0200, 2017-03-15 00:00:00 +0200, 2017-03-22 00:00:00 +0200, 2017-03-29 00:00:00 +0300, 2017-04-05 00:00:00 +0300, 2017-04-12 00:00:00 +0300, 2017-04-19 00:00:00 +0300, 2017-04-26 00:00:00 +0300, 2017-05-03 00:00:00 +0300, 2017-05-10 00:00:00 +0300, 2017-05-17 00:00:00 +0300, 2017-05-24 00:00:00 +0300, 2017-05-31 00:00:00 +0300, 2017-06-07 00:00:00 +0300, 2017-06-14 00:00:00 +0300, 2017-06-21 00:00:00 +0300, 2017-06-28 00:00:00 +0300, 2017-07-05 00:00:00 +0300, 2017-07-12 00:00:00 +0300, 2017-07-19 00:00:00 +0300]
range(Time.parse('2017-07-01'))
# => [2017-07-01 00:00:00 +0300, 2017-07-02 00:00:00 +0300, 2017-07-03 00:00:00 +0300, 2017-07-04 00:00:00 +0300, 2017-07-05 00:00:00 +0300, 2017-07-06 00:00:00 +0300, 2017-07-07 00:00:00 +0300, 2017-07-08 00:00:00 +0300, 2017-07-09 00:00:00 +0300, 2017-07-10 00:00:00 +0300, 2017-07-11 00:00:00 +0300, 2017-07-12 00:00:00 +0300, 2017-07-13 00:00:00 +0300, 2017-07-14 00:00:00 +0300, 2017-07-15 00:00:00 +0300, 2017-07-16 00:00:00 +0300, 2017-07-17 00:00:00 +0300, 2017-07-18 00:00:00 +0300, 2017-07-19 00:00:00 +0300]
```
...so, what's wrong with this?..

**Comment by kenn** [comment] 2017-07-19 08:39
```ruby
> range(190.days.ago)
=> [Tue, 10 Jan 2017 08:32:27 UTC +00:00,
 2017-02-10 08:32:27 +0000,
 2017-03-10 08:32:27 +0000,
 2017-04-10 08:32:27 +0000,
 2017-05-10 08:32:27 +0000,
 2017-06-10 08:32:27 +0000,
 2017-07-10 08:32:27 +0000]

> range(200.days.ago)
=> [Sat, 31 Dec 2016 08:32:31 UTC +00:00,
 2017-01-31 08:32:31 +0000,
 2017-02-28 08:32:31 +0000,
 2017-03-28 08:32:31 +0000,
 2017-04-28 08:32:31 +0000,
 2017-05-28 08:32:31 +0000,
 2017-06-28 08:32:31 +0000]
```

Notice the second call doesn't contain July.

**Comment by zverok** [comment] 2017-07-19 12:50
With `..` ranges in method `range` it will produce:
```ruby
range(190.days.ago)
# => [2017-01-10 15:49:53 +0200, 2017-02-10 15:49:53 +0200, 2017-03-10 15:49:53 +0200, 2017-04-10 15:49:53 +0200, 2017-05-10 15:49:53 +0200, 2017-06-10 15:49:53 +0200, 2017-07-10 15:49:53 +0200, 2017-07-19 15:49:53 +0300]
range(200.days.ago)
# => [2016-12-31 15:49:45 +0200, 2017-01-31 15:49:45 +0200, 2017-02-28 15:49:45 +0200, 2017-03-28 15:49:45 +0200, 2017-04-28 15:49:45 +0200, 2017-05-28 15:49:45 +0200, 2017-06-28 15:49:45 +0200, 2017-07-19 15:49:45 +0300]
```
But you mean that now, for the first one (`190.days.ago`), it contains July two times, and you expect that "month" sequence should contain each month exactly once?..

**Comment by kenn** [comment] 2017-07-19 14:28
> But you mean that now, for the first one (190.days.ago), it contains July two times, and you expect that "month" sequence should contain each month exactly once?

Yep.

**Comment by zverok** [comment] 2017-07-19 14:35
Hm, ok, I've got your point, thanks. I need to think about it for a few moments. Please ping me if I'll be silent more than for a day or two.

**Comment by kenn** [comment] 2017-07-19 14:40
I now realize that `TimeMath.month.sequence(since...Time.current, expand: true)` returns what I want exactly. But I think `expand: true` is an obscure option, and using `...` to exclude the future month is kinda silly for the purpose. My requirement is pretty straightforward, and I truly believe that `..` should just work that way.

**Comment by zverok** [comment] 2017-07-20 16:13
Hm. I believe you were really convincing here. Please check current `develop` branch. It has `Sequence` behavior simplified: edges are now always rounded (`from` always `floor`ed, `to` `floor`ed or `ceil`ed, depending on `...` vs `..`), I now believe this behavior should be more predictable for most of real-life cases.

WDYT?..

**Comment by kenn** [comment] 2017-07-21 06:36
I'm still curious why you want `ceil`, which is effectively **future**? We don't usually deal with future for [time series ](https://en.wikipedia.org/wiki/Time_series)data, especially for `sequence`. You mentioned you needed it for your previous work, but I haven't been convinced by it. I even suspect the code might read better if you have a chance to rewrite it with all `floor`. 😉

Given any time between `2000-01-01T00:00:00` and `2000-01-01T23:59:59.999`, if you pass it to group SQL function like `group.('DATE(created_at)')` or `group('YEAR(created_at)', 'MONTH(created_at)')`, it just works. I'll never need `2000-01-02`.

`floor` is the most powerful, work with any group functions, on both Ruby and SQL. `ceil` only works with inequality expression like `<` or `>` - disproportionately useless.

If you truly need the result of `ceil`, you can do `TimeMath.month(a..b).last.advance(month: 1)` and it makes even better sense to me.

**Comment by zverok** [comment] 2017-07-23 10:17
> I'm still curious why you want ceil, which is effectively **future**?

My reasoning here goes like this:
1. Consider today (Jul 23) I want to do a monthly chart of something from the beginning of the year.
2. Most of the time, there are two clear cases, depending on the task:
a. include current month (July 1-23), because we need entire data
b. exclude current month (e.g. last month on chart would be June), because we work only with full months data
3. I want to express those two cases as clear as possible. So, the idea was that Ruby's ranges "include end"/"exclude end" is clear enough to do this:
```ruby
# include current month:
TimeMath.month.sequence(Time.parse('2017-01-01')..Time.now)
# => #<TimeMath::Sequence month (2017-01-01 00:00:00 +0200 - 2017-08-01 00:00:00 +0300)>

# include only full monthes:
TimeMath.month.sequence(Time.parse('2017-01-01')...Time.now)
 => #<TimeMath::Sequence month (2017-01-01 00:00:00 +0200 - 2017-07-01 00:00:00 +0300)>
```
IDK, maybe in the first case it would be cleaner to have 
```ruby
# => #<TimeMath::Sequence month (2017-01-01 00:00:00 +0200 - 2017-07-23 13:17:00 +0300)>
```
e.g. explicitly wrap it by `Time.now`?..

But I believe that both cases (include last unfinished period/exclude last period) are equally important.

**Comment by kenn** [comment] 2017-07-24 05:32
> a. include current month (July 1-23), because we need entire data
> b. exclude current month (e.g. last month on chart would be June), because we work only with full months data

OK great, this is exactly what I want. We're on the same page here.

Now the debate is whether the last element for `..` should be `2017-08-01` or `2017-07-01`. You vote for `August` and I vote for `July`.

Assuming that `..` ends with July and `...` ends with June, I would do this:

```ruby
from = Time.parse('2017-01-01')
to = Time.current

events = Event.where('created_at >= ? AND created_at < ?', from, to)
  .group('YEAR(created_at)', 'MONTH(created_at)').count
# {[2017, 2]=>1, [2017, 3]=>4, [2017, 6]=>3, [2017, 7]=>11}

@inclusive_data = TimeMath.month.sequence(from..to).each do |i|
  [i, events[[i.year, i.month]] || 0]
end.to_h
# {[2017, 1]=>0, [2017, 2]=>1, [2017, 3]=>4, [2017, 4]=>0, [2017, 5]=>0, [2017, 6]=>3, [2017, 7]=>11}

@exclusive_data = TimeMath.month.sequence(from...to).each do |i|
  [i, events[[i.year, i.month]] || 0]
end.to_h
# {[2017, 1]=>0, [2017, 2]=>1, [2017, 3]=>4, [2017, 4]=>0, [2017, 5]=>0, [2017, 6]=>3}

<%= line_chart @inclusive_data %>
<%= line_chart @exclusive_data %>
```

But how can I do the same if `..` returns August?

**Comment by zverok** [comment] 2017-07-24 13:20
:philosoraptor:
Well, In my current model, you can do this:
```ruby
TimeMath.month.sequence(from...to).ranges # => all ranges excluding July
TimeMath.month.sequence(from..to).ranges # => all ranges including July
```
...but in fact your example makes sense for me. Thinking of it.

**Comment by zverok** [comment] 2017-07-29 13:20
Please check `develop` branch now. It is updated according to our discussions... And, to be honest, code and docs became much cleaner, which means it was a right decision.

**Comment by kenn** [comment] 2017-07-30 10:49
Yay! Thank you! 🎉 🙌 🎉

**Comment by zverok** [comment] 2017-07-30 13:47
OK, merged and released new gem version. Thank you for meaningful discussion. Without actual gem use cases some architectural solutions are hard to guess.

**Closed by zverok** 2017-07-30 13:47 UTC
